version: '3'
services:
    db:
        image: 'postgres:9.6.2'
        ports:
          - '5432'
    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
         - .:/onboard
         - node_mod_vol:/onboard/node_modules
        ports:
         - "3000:3000"
        entrypoint: ./scripts/wait_for_postgres.sh db 5432
        depends_on:
         - db
volumes:
  node_mod_vol:
