development: &default
  adapter: postgresql
  encoding: unicode
  database: onboard_development
  pool: 5
  username: postgres
  password:
  host: db

production:
  <<: *default
  database: onboard_production

test:
  <<: *default
  database: onboard_test

